import type { Action, Subject } from "./authorization";

export interface RouteEntry {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  action: Action;
  subject: Subject;
  mutating: boolean;
  staffOnly: boolean;
  audited?: boolean;
}

const staticRoutes: RouteEntry[] = [
  {
    method: "GET",
    path: "/:locale",
    action: "read",
    subject: "marketing",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/login",
    action: "read",
    subject: "marketing",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/register",
    action: "read",
    subject: "marketing",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/legal",
    action: "read",
    subject: "marketing",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/legal/:document",
    action: "read",
    subject: "marketing",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/card/:token",
    action: "read",
    subject: "card_verification",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/directory",
    action: "read",
    subject: "catalogue",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/directory/:slug",
    action: "read",
    subject: "catalogue",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/dashboard",
    action: "read",
    subject: "own_profile",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/profile",
    action: "read",
    subject: "own_profile",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/profile",
    action: "read",
    subject: "own_card",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/profile",
    action: "read",
    subject: "own_subscription",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/referrals",
    action: "read",
    subject: "own_referral",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/checkout/success",
    action: "read",
    subject: "own_subscription",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/checkout/canceled",
    action: "read",
    subject: "own_subscription",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/company/new",
    action: "create",
    subject: "own_company",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:registerCompanyAction",
    action: "create",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:listOwnSessionsAction",
    action: "read",
    subject: "own_session",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:revokeOwnSessionAction",
    action: "delete",
    subject: "own_session",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:revokeOtherSessionsAction",
    action: "delete",
    subject: "own_session",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:saveCompanyDraftAction",
    action: "create",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:getCompanyDraftAction",
    action: "create",
    subject: "own_company",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:discardCompanyDraftAction",
    action: "create",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:moderateCompanyAction:approve",
    action: "approve",
    subject: "company",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:moderateCompanyAction:reject",
    action: "reject",
    subject: "company",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:setCompanyShowcaseAction",
    action: "approve",
    subject: "company",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:hideCompanyAction",
    action: "approve",
    subject: "company",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:unhideCompanyAction",
    action: "approve",
    subject: "company",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:staffEditCompanyAction",
    action: "approve",
    subject: "company",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:ownerEditCompanyAction",
    action: "update",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:approveCompanyChangesAction",
    action: "approve",
    subject: "company",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:rejectCompanyChangesAction",
    action: "reject",
    subject: "company",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/admin",
    action: "read",
    subject: "finance_dashboard",
    mutating: false,
    staffOnly: true,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/admin/support",
    action: "read",
    subject: "moderation",
    mutating: false,
    staffOnly: true,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/admin/categories",
    action: "manage_reference_data",
    subject: "reference_data",
    mutating: false,
    staffOnly: true,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/admin/companies",
    action: "read",
    subject: "company",
    mutating: false,
    staffOnly: true,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/admin/members",
    action: "read",
    subject: "member",
    mutating: false,
    staffOnly: true,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/admin/staff",
    action: "manage_staff",
    subject: "staff_user",
    mutating: false,
    staffOnly: true,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/admin/referrals",
    action: "approve",
    subject: "referral",
    mutating: false,
    staffOnly: true,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/admin/audit",
    action: "read",
    subject: "audit_log",
    mutating: false,
    staffOnly: true,
  },
  {
    method: "GET",
    path: "/:locale/dashboard/admin/flags",
    action: "manage_flags",
    subject: "feature_flag",
    mutating: false,
    staffOnly: true,
  },
  {
    method: "POST",
    path: "action:createReferralAction",
    action: "send_referral",
    subject: "referral",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:moderateReferralAction:approve",
    action: "approve",
    subject: "referral",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:moderateReferralAction:reject",
    action: "reject",
    subject: "referral",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:barReferralSenderAction",
    action: "block",
    subject: "referral",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:blockMemberAction",
    action: "block",
    subject: "member",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:blockMemberAction",
    action: "unblock",
    subject: "member",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:revokeCardAction",
    action: "revoke",
    subject: "card",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:reissueCardAction",
    action: "reissue",
    subject: "card",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:respondToReferralAction",
    action: "update",
    subject: "own_referral",
    mutating: true,
    staffOnly: false,
  },
  // The inbox (FR-099). Both are scoped to the caller's own rows; there is
  // deliberately no entry that reads another member's notifications.
  {
    method: "POST",
    path: "action:markNotificationReadAction",
    action: "update",
    subject: "own_notification",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:markAllNotificationsReadAction",
    action: "update",
    subject: "own_notification",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:createVipCheckoutAction",
    action: "create",
    subject: "own_subscription",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:createCheckoutSessionAction",
    action: "create",
    subject: "own_subscription",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:createPortalSessionAction",
    action: "read",
    subject: "own_subscription",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:updateProfileAction",
    action: "update",
    subject: "own_profile",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:updatePersonalInfoAction",
    action: "update",
    subject: "own_profile",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:initiatePhoneChangeAction",
    action: "update",
    subject: "own_profile",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:verifyOldPhoneAction",
    action: "update",
    subject: "own_profile",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:verifyNewPhoneAction",
    action: "update",
    subject: "own_profile",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:requestAccountDeletionAction",
    action: "delete",
    subject: "own_profile",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:createStaffAction",
    action: "manage_staff",
    subject: "staff_user",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:setStaffRoleAction",
    action: "manage_staff",
    subject: "staff_user",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:setStaffStatusAction",
    action: "manage_staff",
    subject: "staff_user",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:createCategoryAction",
    action: "manage_reference_data",
    subject: "reference_data",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:toggleCategoryStatusAction",
    action: "manage_reference_data",
    subject: "reference_data",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:deleteCategoryAction",
    action: "manage_reference_data",
    subject: "reference_data",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:createCountryAction",
    action: "manage_reference_data",
    subject: "reference_data",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:toggleCountryStatusAction",
    action: "manage_reference_data",
    subject: "reference_data",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:deleteCountryAction",
    action: "manage_reference_data",
    subject: "reference_data",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:createCityAction",
    action: "manage_reference_data",
    subject: "reference_data",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:toggleCityStatusAction",
    action: "manage_reference_data",
    subject: "reference_data",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:deleteCityAction",
    action: "manage_reference_data",
    subject: "reference_data",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "action:setPlanPriceAction",
    action: "manage_prices",
    subject: "plan_price",
    mutating: true,
    staffOnly: true,
    audited: true,
  },
  {
    method: "GET",
    path: "/api/export/member",
    action: "read",
    subject: "own_profile",
    mutating: false,
    staffOnly: false,
  },
  {
    // Always the caller's own avatar - the route takes no target id, so
    // there is no other member's file this entry could leak (ADR 0021).
    method: "GET",
    path: "/api/avatar",
    action: "read",
    subject: "own_profile",
    mutating: false,
    staffOnly: false,
  },
  {
    // Company gallery photo (ADR 0022): catalogue content, member-gated like
    // the catalogue, publishable-gated per image inside the handler.
    method: "GET",
    path: "/api/company-image/:imageId",
    action: "read",
    subject: "catalogue",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:uploadCompanyImageAction",
    action: "update",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:deleteCompanyImageAction",
    action: "update",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  {
    // Company logo (ADR 0023): public brand imagery once the company is
    // publishable - the marketing landing shows it to guests - so no session
    // is required; the handler applies the approved+paid test per company.
    method: "GET",
    path: "/api/company-logo/:companyId",
    action: "read",
    subject: "marketing",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:uploadCompanyLogoAction",
    action: "update",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:removeCompanyLogoAction",
    action: "update",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  // Onboarding media staging (ADR 0024). Every entry is scoped to the
  // caller's own draft - the object key is derived from the session.
  {
    method: "GET",
    path: "/api/draft-media/:slot",
    action: "create",
    subject: "own_company",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:uploadDraftLogoAction",
    action: "create",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:removeDraftLogoAction",
    action: "create",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:uploadDraftImageAction",
    action: "create",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "POST",
    path: "action:deleteDraftImageAction",
    action: "create",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  {
    // City names for the onboarding picker (ADR 0025): reference data, read
    // through a Server Action so the provider key never reaches the browser.
    method: "POST",
    path: "action:listCitiesForCountryAction",
    action: "create",
    subject: "own_company",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/api/admin/export/member/:memberId",
    action: "export_data",
    subject: "member",
    mutating: false,
    staffOnly: true,
    audited: true,
  },
  {
    method: "POST",
    path: "/api/webhooks/stripe",
    action: "create",
    subject: "subscription",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/api/cron/outbox-drain",
    action: "update",
    subject: "subscription",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/api/cron/subscription-lapse",
    action: "update",
    subject: "subscription",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/api/cron/billing-reconciliation",
    action: "update",
    subject: "subscription",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/api/cron/referrals",
    action: "delete",
    subject: "referral",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/api/cron/retention",
    action: "delete",
    subject: "own_company",
    mutating: true,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/health/live",
    action: "read",
    subject: "marketing",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/health/ready",
    action: "read",
    subject: "marketing",
    mutating: false,
    staffOnly: false,
  },
  {
    // Unauthenticated like its two siblings, because synthetic monitoring has
    // no session to present. It discloses queue depth and the age of the
    // oldest waiting row - operational shape, no member data.
    method: "GET",
    path: "/health/deep",
    action: "read",
    subject: "marketing",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/.well-known/security.txt",
    action: "read",
    subject: "marketing",
    mutating: false,
    staffOnly: false,
  },
  {
    method: "GET",
    path: "/robots.txt",
    action: "read",
    subject: "marketing",
    mutating: false,
    staffOnly: false,
  },
];

const routes: RouteEntry[] = [];

export function registerRoute(entry: RouteEntry): void {
  routes.push(entry);
}

export function getRegisteredRoutes(): readonly RouteEntry[] {
  return [...staticRoutes, ...routes];
}

export function getMutatingStaffRoutes(): readonly RouteEntry[] {
  return getRegisteredRoutes().filter((r) => r.mutating && r.staffOnly);
}

export function clearRegistry(): void {
  routes.length = 0;
}
